import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import "highlight.js/styles/monokai-sublime.css";
import { icons } from "lucide-react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "bLOG9",
  description: "Generated by create next app",
  icons: {
    icon: "/blog.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
