import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import "highlight.js/styles/monokai-sublime.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lyeana Blog Webiste",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
